site_name: loca-data-api
site_description: Data API for local, you can write unittest for AWS Aurora Serverless's Data API

theme:
    name: 'material'
    palette:
      primary: 'light blue'
      accent: 'light blue'
    analytics:
      gtag: 275257853
markdown_extensions:
  - codehilite

repo_name: koxudaxi/loca-data-api
repo_url: https://github.com/koxudaxi/local-data-api
site_url: https://koxudaxi.github.io/local-data-api

nav:
    - local-data-api: 'index.md'