name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: koxudaxi/local-data-api
          tag-semver: |
            {{raw}}
      - name: Cache
        uses: actions/cache@v1.1.2
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: build and test 
        run: ./gradlew clean shadowJar test jacocoTestReport
        working-directory: ./kotlin/local-data-api/
      - name: Login to DockerHub
        if: github.event_name  == 'push tag'
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name == 'push tag' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          context: ./kotlin/local-data-api
